[package]
name = "dll-scanner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true
jwalk.workspace = true
once_cell.workspace = true
sha2.workspace = true
pe-version = { path = "../pe-version" }

[dev-dependencies]
tempfile.workspace = true
