[package]
name = "dll-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
reqwest.workspace = true
sha2.workspace = true
md-5.workspace = true
chrono.workspace = true
tracing.workspace = true
tokio = { workspace = true }
zip.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
